name: Replace Secrets in Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  replace-secrets:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Read appsettings.json
      id: read_appsettings
      run: |
        $content = Get-Content -Path "DemoApp/DemoApp/appsettings.json" -Raw
        echo "::set-output name=content::$content"
      shell: pwsh
        
    - name: Replace secrets
      id: replace_secrets
      run: |
        $content = '${{ steps.read_appsettings.outputs.content }}'
        $content = $content -replace '\$\{\{\s*DBSERVERNAME\s*\}\}', '${{ secrets.DBSERVERNAME }}'
        $content = $content -replace '\$\{\{\s*SYNCFUSIONKEY\s*\}\}', '${{ secrets.SYNCFUSIONKEY }}'
        $content | Set-Content -Path "DemoApp/DemoApp/appsettings.json"
      shell: pwsh
      
    - name: Verify file update
      run: |
        if (!(Test-Path "DemoApp/DemoApp/appsettings.json")) {
          echo "Error: appsettings.json not found!"
          exit 1
        }
        echo "Successfully updated appsettings.json"
      shell: pwsh
