name: Replace Secrets in appsettings.json

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  replace-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace secrets in appsettings.json
      run: |
        # Define the path to appsettings.json
        APPSETTINGS_FILE="DemoApp/DemoApp/appsettings.json"
        
        # Replace placeholders with secret values
        sed -i "s|\${{ DBSERVERNAME }}|${{ secrets.DBSERVERNAME }}|g" $APPSETTINGS_FILE
        sed -i "s|\${{ SYNCFUSIONKEY }}|${{ secrets.SYNCFUSIONKEY }}|g" $APPSETTINGS_FILE

    - name: Verify replacement (optional)
      run: cat DemoApp/DemoApp/appsettings.json
