name: Replace Secrets in appsettings.json

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  replace-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace secrets in appsettings.json
      run: |
        sed -i "s|\${{ secrets.DBSERVERNAME }}|${{ secrets.DBSERVERNAME }}|g" DemoApp/DemoApp/appsettings.json
        sed -i "s|\${{ secrets.SYNCFUSIONKEY }}|${{ secrets.SYNCFUSIONKEY }}|g" DemoApp/DemoApp/appsettings.json
